backend:
  name: github
  repo: sameerlinger/linger-wp
  branch: main
  base_url: https://linger-wp-oauth.onrender.com

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Properties & Pages"
    folder: "src/content"
    create: false
    delete: false
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    delete: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list", default: [] }
      - { label: "Body", name: "body", widget: "markdown" }
